server:
  port: 3001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.130/club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Ly4rnHwO3qKDHa94Z7aI3ElaXNQNav4uwxiQOI4zYpvBCV2yNAaGMhPHZ8nyYuoVOzeUsTNu7v0Vc+Zh/+NWlA==  #加密的数据库密码
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 192.168.101.130
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 1234
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

#数据库密码加密公钥
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJji6ELZ8miaNb8GQVEJcuYNWIQsToifCQvYc0Y0gEZBrlMUBv6OUr6noWVxJwK/zS5F07Jhgp1WjOf2Rtv200MCAwEAAQ==

# 日志配置
logging:
  config:
    classpath: log4j2-spring.xml
# mybatis-plus的sql日志（不过yml文件配置sql打印参数要与问号一一对应很难观察,于是专门在infra下配置mybatis的sql打印去打印）
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# sa-token配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 指定 token 提交时的前缀
  token-prefix: jichi
  # 是否输出操作日志
  is-log: true

